version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - cd frontend && npm run build
artifacts:
  files:
    - deploy/appspec.yml
    - deploy/afterInstall.sh
    - api
    - deploy/build
    - deploy/droneX.nginx.conf
  discard-paths: no