version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - cd frontend && npm run deploy && cd ..
      - cd api && npm run deploy
artifacts:
  files:
    - api/api.zip
    - frontend/frontend.zip
    - deploy/appspec.yml
    - deploy/beforeInstall.sh
    - deploy/afterInstall.sh
    - deploy/droneX.nginx.conf
  discard-paths: yes